package tugasuas;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class AppLaundry extends javax.swing.JFrame {
    public int harga,berat,ttlbyr;
    public void load_table() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("NO");
        model.addColumn("KODE PELANGGAN");
        model.addColumn("TANGGAL");
        model.addColumn("NAMA PELANGGAN");
        model.addColumn("NO. TELP");
        model.addColumn("ALAMAT");
        model.addColumn("BERAT PAKAIAN");
        model.addColumn("HARGA");
        model.addColumn("TOTAL BAYAR");
        
        try {
            int no=1;
            String sql = "select * from laundry";
            java.sql.Connection conn=(Connection)koneksi.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                model.addRow(new Object[]{no++,res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5),
                    res.getString(6),res.getString(7),res.getString(8)});
            }
            tbltransaksi.setModel(model);
        } catch (Exception e) {
        }    
    }
    private void tgl(){
        Date ys=new Date();
        SimpleDateFormat s=new SimpleDateFormat("yyyy-mm-dd");
        txttgl.setText(s.format(ys));
    }
    public void kosong(){
        txtberat.setText("");
        txtharga.setText("");
        txtnotlp.setText("");
        txtttlbyr.setText("");
        txtkodepel.setText("");
        txtnamapel.setText("");
        txttgl.setText("");
        taalamat.setText("");
    }

    public AppLaundry() {
        super("App Laundry");
        initComponents();
        setResizable(false);
        setSize(840, 687);
        setLocationRelativeTo(null);
        tgl();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        txttgl1 = new javax.swing.JLabel();
        txtkodepel1 = new javax.swing.JLabel();
        txtnamapel1 = new javax.swing.JLabel();
        txtnotlp1 = new javax.swing.JLabel();
        taalamat1 = new javax.swing.JLabel();
        txtberat = new javax.swing.JTextField();
        txtnamapel = new javax.swing.JTextField();
        txtkodepel = new javax.swing.JTextField();
        txtttlbyr = new javax.swing.JTextField();
        txtberat1 = new javax.swing.JLabel();
        txtharga1 = new javax.swing.JLabel();
        txttgl = new javax.swing.JTextField();
        txtnotlp = new javax.swing.JTextField();
        txtharga = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taalamat = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbltransaksi = new javax.swing.JTable();
        btnSearch = new javax.swing.JButton();
        tfSearch = new javax.swing.JTextField();
        btnTotalBayar = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 153));
        setUndecorated(true);
        getContentPane().setLayout(null);

        txttgl1.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txttgl1.setForeground(new java.awt.Color(255, 255, 255));
        txttgl1.setText("Tanggal");
        getContentPane().add(txttgl1);
        txttgl1.setBounds(20, 100, 70, 15);

        txtkodepel1.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtkodepel1.setForeground(new java.awt.Color(255, 255, 255));
        txtkodepel1.setText("Kode Pelanggan");
        getContentPane().add(txtkodepel1);
        txtkodepel1.setBounds(20, 150, 110, 20);

        txtnamapel1.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtnamapel1.setForeground(new java.awt.Color(255, 255, 255));
        txtnamapel1.setText("Nama Pelanggan");
        getContentPane().add(txtnamapel1);
        txtnamapel1.setBounds(20, 200, 110, 15);

        txtnotlp1.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtnotlp1.setForeground(new java.awt.Color(255, 255, 255));
        txtnotlp1.setText("Nomor Telepon");
        getContentPane().add(txtnotlp1);
        txtnotlp1.setBounds(20, 250, 110, 15);

        taalamat1.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        taalamat1.setForeground(new java.awt.Color(255, 255, 255));
        taalamat1.setText("Alamat");
        getContentPane().add(taalamat1);
        taalamat1.setBounds(20, 300, 70, 15);

        txtberat.setForeground(new java.awt.Color(0, 153, 153));
        getContentPane().add(txtberat);
        txtberat.setBounds(490, 120, 210, 40);

        txtnamapel.setForeground(new java.awt.Color(0, 153, 153));
        txtnamapel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamapelActionPerformed(evt);
            }
        });
        getContentPane().add(txtnamapel);
        txtnamapel.setBounds(130, 190, 210, 40);

        txtkodepel.setForeground(new java.awt.Color(0, 153, 153));
        txtkodepel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkodepelActionPerformed(evt);
            }
        });
        getContentPane().add(txtkodepel);
        txtkodepel.setBounds(130, 140, 210, 40);

        txtttlbyr.setForeground(new java.awt.Color(0, 153, 153));
        getContentPane().add(txtttlbyr);
        txtttlbyr.setBounds(490, 220, 210, 40);

        txtberat1.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtberat1.setForeground(new java.awt.Color(0, 102, 102));
        txtberat1.setText("Berat Pakaian (Kg)");
        getContentPane().add(txtberat1);
        txtberat1.setBounds(370, 130, 120, 15);

        txtharga1.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtharga1.setForeground(new java.awt.Color(0, 102, 102));
        txtharga1.setText("Harga/(Kg)");
        getContentPane().add(txtharga1);
        txtharga1.setBounds(370, 180, 80, 15);

        txttgl.setForeground(new java.awt.Color(0, 153, 153));
        getContentPane().add(txttgl);
        txttgl.setBounds(130, 90, 210, 40);

        txtnotlp.setForeground(new java.awt.Color(0, 153, 153));
        getContentPane().add(txtnotlp);
        txtnotlp.setBounds(130, 240, 210, 40);

        txtharga.setForeground(new java.awt.Color(0, 153, 153));
        getContentPane().add(txtharga);
        txtharga.setBounds(490, 170, 210, 40);

        jButton3.setBackground(new java.awt.Color(0, 102, 102));
        jButton3.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Simpan");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(370, 300, 100, 31);

        jButton4.setBackground(new java.awt.Color(0, 102, 102));
        jButton4.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Update");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(480, 300, 100, 31);

        jButton5.setBackground(new java.awt.Color(0, 102, 102));
        jButton5.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Delete");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(590, 300, 110, 31);

        jButton6.setBackground(new java.awt.Color(0, 102, 102));
        jButton6.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("View");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(710, 300, 100, 31);

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("LAUNDRY");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(310, 20, 240, 40);

        jButton1.setBackground(new java.awt.Color(0, 102, 102));
        jButton1.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("CANCEL");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(730, 120, 80, 40);

        btnHome.setBackground(new java.awt.Color(0, 102, 102));
        btnHome.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        btnHome.setForeground(new java.awt.Color(255, 255, 255));
        btnHome.setText("HOME");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        getContentPane().add(btnHome);
        btnHome.setBounds(730, 220, 80, 40);

        taalamat.setColumns(20);
        taalamat.setForeground(new java.awt.Color(0, 153, 153));
        taalamat.setRows(5);
        jScrollPane1.setViewportView(taalamat);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(130, 290, 210, 83);

        tbltransaksi.setForeground(new java.awt.Color(0, 153, 153));
        tbltransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NO", "KODE PELANGGAN", "TANGGAL", "NAMA PELANGGAN", "NO. TELP", "ALAMAT", "BERAT PAKAIAN", "HARGA", "TOTAL BAYAR"
            }
        ));
        jScrollPane2.setViewportView(tbltransaksi);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(20, 460, 800, 190);

        btnSearch.setBackground(new java.awt.Color(255, 255, 255));
        btnSearch.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(0, 102, 102));
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch);
        btnSearch.setBounds(730, 410, 90, 31);
        getContentPane().add(tfSearch);
        tfSearch.setBounds(520, 410, 200, 30);

        btnTotalBayar.setBackground(new java.awt.Color(0, 102, 102));
        btnTotalBayar.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        btnTotalBayar.setForeground(new java.awt.Color(255, 255, 255));
        btnTotalBayar.setText("Total Bayar");
        btnTotalBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalBayarActionPerformed(evt);
            }
        });
        getContentPane().add(btnTotalBayar);
        btnTotalBayar.setBounds(370, 220, 100, 40);

        jButton7.setBackground(new java.awt.Color(0, 102, 102));
        jButton7.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("EXIT");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(730, 170, 80, 40);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel2);
        jPanel2.setBounds(360, 90, 460, 280);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setForeground(new java.awt.Color(0, 153, 153));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 840, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnamapelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamapelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamapelActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       try{
            String sql = "update laundry set kode_pelanggan=?, tanggal=?, nama_pelanggan=?, no_telp=?, alamat=?, berat_pakaian=?, harga=?, total_bayar=? "
                    + "where kode_pelanggan='"+txtkodepel.getText()+"'";
            java.sql.Connection conn=(Connection)koneksi.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.setString(1, txtkodepel.getText());
            pst.setString(2, txttgl.getText());
            pst.setString(3, txtnamapel.getText());
            pst.setString(4, txtnotlp.getText());
            pst.setString(5, taalamat.getText());
            pst.setString(6, txtberat.getText());
            pst.setString(7, txtharga.getText());
            pst.setString(8, txtttlbyr.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "BERHASIL UPDATE DATA", "Pesan", JOptionPane.INFORMATION_MESSAGE);
       }
         catch(Exception e){
            JOptionPane.showMessageDialog(null, "GAGAL UPDATE DATA" + e.getMessage(), "Pesan", JOptionPane.ERROR_MESSAGE);
        }
        kosong();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtkodepelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkodepelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkodepelActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     try{
            String sql = "insert into laundry(kode_pelanggan, tanggal, nama_pelanggan, no_telp, alamat, berat_pakaian, harga, total_bayar) values(?,?,?,?,?,?,?,?)";
            java.sql.Connection conn=(Connection)koneksi.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.setString(1, txtkodepel.getText());
            pst.setString(2, txttgl.getText());
            pst.setString(3, txtnamapel.getText());
            pst.setString(4, txtnotlp.getText());
            pst.setString(5, taalamat.getText());
            pst.setString(6, txtberat.getText());
            pst.setString(7, txtharga.getText());
            pst.setString(8, txtttlbyr.getText());
            pst.executeUpdate();
             JOptionPane.showMessageDialog(null, "BERHASIL MENYIMPAN DATA", "Pesan", JOptionPane.INFORMATION_MESSAGE);
       }catch(Exception e){
          JOptionPane.showMessageDialog(null, "GAGAL MENYIMPAN DATA" + e.getMessage(), "Pesan", JOptionPane.ERROR_MESSAGE);
    }
     kosong();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
       new formUtama().setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_btnHomeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        kosong();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        load_table();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        try{
            java.sql.Connection conn=(Connection)koneksi.configDB();
            java.sql.Statement stm=conn.createStatement();
            String sql = "SELECT * FROM laundry WHERE kode_pelanggan like '%"+tfSearch.getText()+"%'" + "OR nama_pelanggan like '%"+tfSearch.getText()+"%'";
            java.sql.ResultSet res=stm.executeQuery(sql);
            DefaultTableModel dtm = (DefaultTableModel) tbltransaksi.getModel();
            dtm.setRowCount(0);
            int no = 1;

            while(res.next())
            {
                txtkodepel.setText(res.getString("kode_pelanggan"));
                 txttgl.setText(res.getString("tanggal"));
                 txtnamapel.setText(res.getString("nama_pelanggan"));
                 txtnotlp.setText(res.getString("no_telp"));
                 taalamat.setText(res.getString("alamat"));
                 txtberat.setText(res.getString("berat_pakaian"));
                 txtharga.setText(res.getString("harga"));
                 txtttlbyr.setText(res.getString("total_bayar"));
               dtm.addRow(new Object[]{no++,res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5),res.getString(6),res.getString(7),
                   res.getString(8)});
            }
            res.close();
            tfSearch.setText("");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "DATA TIDAK DITEMUKAN \n" + e.getMessage(), "Pesan", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
         int confirm = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin menghapus data tersebut?", "Konfirmasi", JOptionPane.YES_NO_OPTION, 
                 JOptionPane.QUESTION_MESSAGE);
        if (confirm == 0) {
            try {
                String sql = "delete from laundry where kode_pelanggan='"+txtkodepel.getText()+"'";
                java.sql.Connection conn=(Connection)koneksi.configDB();
                java.sql.PreparedStatement pst=conn.prepareStatement(sql);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "BERHASIL HAPUS DATA", "Pesan", JOptionPane.INFORMATION_MESSAGE);
                txtkodepel.setText("");
                txttgl.setText("");
                txtnamapel.setText("");
                txtnotlp.setText("");
                taalamat.setText("");
                txtberat.setText("");
                txtharga.setText("");
                txtttlbyr.setText("");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "GAGAL HAPUS DATA" + e.getMessage(), "Pesan", JOptionPane.ERROR_MESSAGE);
            }
        }
        kosong();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnTotalBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalBayarActionPerformed
        berat=Integer.parseInt(txtberat.getText());
        harga=Integer.parseInt(txtharga.getText());
        ttlbyr=berat*harga;
        txtttlbyr.setText(Integer.toString(ttlbyr));
    }//GEN-LAST:event_btnTotalBayarActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this,
           "Konfirmasi Keluar Aplikasi",
            "Yakin untuk keluar dari program",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);

                if (confirm == JOptionPane.YES_OPTION) {
                 System.exit(0);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppLaundry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppLaundry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppLaundry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppLaundry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppLaundry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnTotalBayar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea taalamat;
    private javax.swing.JLabel taalamat1;
    private javax.swing.JTable tbltransaksi;
    private javax.swing.JTextField tfSearch;
    private javax.swing.JTextField txtberat;
    private javax.swing.JLabel txtberat1;
    private javax.swing.JTextField txtharga;
    private javax.swing.JLabel txtharga1;
    private javax.swing.JTextField txtkodepel;
    private javax.swing.JLabel txtkodepel1;
    private javax.swing.JTextField txtnamapel;
    private javax.swing.JLabel txtnamapel1;
    private javax.swing.JTextField txtnotlp;
    private javax.swing.JLabel txtnotlp1;
    private javax.swing.JTextField txttgl;
    private javax.swing.JLabel txttgl1;
    private javax.swing.JTextField txtttlbyr;
    // End of variables declaration//GEN-END:variables

private String sql;
private Connection con;
private Statement st;
private ResultSet rs;
private PreparedStatement ps;
private DefaultTableModel dtm;
}